name: LLM Regression Test

on:
  push:
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: DeepEval CLI Login
        run: |
          echo ${{ secrets.CONFIDENT_API_KEY }} | deepeval login --api-key

      - name: Run DeepEval Unit Tests
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            CONFIDENT_API_KEY: ${{ secrets.CONFIDENT_API_KEY }}
        run: deepeval test run test_file.py
